"use client";
import { useEffect, useMemo, useState } from "react";

type CaseRecord={id:string;category:string;event_date:string|null;source_date_raw:string;title:string|null;topics:string[];source_page_start:number;source_page_end:number;raw_text:string;people:string[];needs_review:boolean};
type Manifest={pages:number;records:number;people_candidates:number;review_queue_count:number};
const notes:Record<string,string>={Nulla:"elhallgatott hír",Parancs:"parancsra készített hír",Kuka:"kidobott hír",Elutasítva:"elutasított hírjavaslat",Hárítás:"hárított manipulációs kísérlet",Manipuláció:"MTI-anyagnak álcázott közlemény",Utasítás:"utasítás",Késleltetve:"késleltetett anyag","Fake news":"hamis hír vagy tudósítás",Cenzúra:"indokolatlan húzás"};
const categories=Object.keys(notes);
const excerpt=(value:string)=>value.replace(/\s+/g," ").trim().slice(0,260)+"…";
const recordDate=(r:CaseRecord)=>r.event_date??r.source_date_raw??"dátum nincs";

export default function Home(){
 const[records,setRecords]=useState<CaseRecord[]>([]);const[manifest,setManifest]=useState<Manifest|null>(null);const[q,setQ]=useState("");const[category,setCategory]=useState("Összes");const[topic,setTopic]=useState("Összes");const[selected,setSelected]=useState<CaseRecord|null>(null);
 useEffect(()=>{Promise.all([fetch("/data/records.json").then(x=>x.json()),fetch("/data/manifest.json").then(x=>x.json())]).then(([items,meta])=>{setRecords(items);setManifest(meta)})},[]);
 const topics=useMemo(()=>[...new Set(records.flatMap(r=>r.topics))].sort(),[records]);
 const filtered=useMemo(()=>records.filter(r=>{const all=`${r.title??""} ${r.raw_text} ${r.people.join(" ")} ${r.topics.join(" ")}`.toLocaleLowerCase("hu");return(category==="Összes"||r.category===category)&&(topic==="Összes"||r.topics.includes(topic))&&(!q||all.includes(q.toLocaleLowerCase("hu")))}),[records,q,category,topic]);
 const counts=useMemo(()=>Object.fromEntries(categories.map(c=>[c,records.filter(r=>r.category===c).length])),[records]);
 const years=useMemo(()=>Object.entries(filtered.filter(r=>r.event_date).reduce<Record<string,number>>((out,r)=>{const y=r.event_date!.slice(0,4);out[y]=(out[y]??0)+1;return out},{})).sort(),[filtered]);const maximum=Math.max(1,...years.map(([,n])=>n));
 return <main>
  <section className="hero"><div><div className="eyebrow">DOKUMENTUMALAPÚ ESETTÁR</div><h1>Narancs csíkos<br/><em>MTI-szerkesztői döntések</em></h1></div><p>A 483 oldalas forrásdokumentum 220, eredeti oldalakkal visszakövethető esetre bontva. A felület a forrás olvasását könnyíti meg; nem helyettesíti azt.</p><div className="source">Forrás: <b>mti-400.pdf</b> · {manifest?`${manifest.pages} oldal · ${manifest.records} eset`:"betöltés…"}</div></section>
  <section className="stats"><Metric value={records.length||"–"} label="feltárt eset"/><Metric value={manifest?.people_candidates||"–"} label="névjelölt"/><Metric value={manifest?.review_queue_count||"–"} label="ellenőrzendő metaadat"/><Metric value="10" label="forráskategória"/></section>
  <section className="controls"><label className="search"><span>Keresés a teljes szövegben</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="név, ügy, helyszín vagy kifejezés"/></label><label><span>Szerkesztői döntés</span><select value={category} onChange={e=>setCategory(e.target.value)}><option>Összes</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Téma</span><select value={topic} onChange={e=>setTopic(e.target.value)}><option>Összes</option>{topics.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>{setQ("");setCategory("Összes");setTopic("Összes")}}>Szűrők törlése</button></section>
  <section className="overview"><div className="panel"><Header no="01" title="Döntéstípusok" small="A forrás saját kategóriái"/><div className="list">{categories.map(c=><button className={`category ${category===c?"active":""}`} onClick={()=>setCategory(category===c?"Összes":c)} key={c}><i className={c.replace(" ","-")}/><b>{c}</b><span>{notes[c]}</span><strong>{counts[c]??0}</strong></button>)}</div></div><div className="panel"><Header no="02" title="Idővonal" small="Csak dátumozott esetek"/><div className="years">{years.map(([year,count])=><div key={year}><span>{year}</span><i><b style={{width:`${count/maximum*100}%`}}/></i><strong>{count}</strong></div>)}</div></div></section>
  <section className="results"><div><span>03</span><h2>Találatok</h2><p>{filtered.length} eset a jelenlegi szűréssel</p></div><p className="method">Minden rekord a PDF eredeti oldaltartományára mutat. A cím- és témajavaslat gépi szabályokkal készült; az „ellenőrzendő” jelölés nem szerkesztői ítélet.</p></section>
  <section className="cards">{filtered.map(r=><article className="card" key={r.id} tabIndex={0} onClick={()=>setSelected(r)} onKeyDown={e=>e.key==="Enter"&&setSelected(r)}><div className="top"><span className={`pill ${r.category.replace(" ","-")}`}>{r.category}</span><span>{recordDate(r)}</span></div><h3>{r.title??"Cím nem azonosítható automatikusan"}</h3><p>{excerpt(r.raw_text)}</p><div className="bottom"><div>{r.topics.map(t=><span className="topic" key={t}>{t}</span>)}</div><span>PDF {r.source_page_start}{r.source_page_start!==r.source_page_end?`–${r.source_page_end}`:""}. oldal</span></div>{r.needs_review&&<em>ellenőrzendő</em>}</article>)}</section>
  {!filtered.length&&records.length>0&&<p className="empty">Nincs találat ezzel a szűréssel.</p>}
  {selected&&<div className="backdrop" onMouseDown={()=>setSelected(null)}><article className="modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button onClick={()=>setSelected(null)} aria-label="Bezárás">×</button><span className={`pill ${selected.category.replace(" ","-")}`}>{selected.category}</span><h2>{selected.title??"Cím nem azonosítható automatikusan"}</h2><p className="meta">Forrás: mti-400.pdf, {selected.source_page_start}{selected.source_page_start!==selected.source_page_end?`–${selected.source_page_end}`:""}. oldal · {recordDate(selected)}</p><div>{selected.topics.map(t=><span className="topic" key={t}>{t}</span>)}</div>{selected.people.length>0&&<p className="meta"><b>Névjelöltek:</b> {selected.people.join(", ")}</p>}<pre>{selected.raw_text}</pre></article></div>}
 </main>
}
function Metric({value,label}:{value:string|number;label:string}){return <div><b>{value}</b><span>{label}</span></div>}
function Header({no,title,small}:{no:string;title:string;small:string}){return <header><div><span>{no}</span><h2>{title}</h2></div><small>{small}</small></header>}
